title: Rainy Day Tabletop
author:
  name: Adam Strautman
  email: 'adam@rainydaytabletop.com'
metadata:
    description: 'We are a group of friends that comes together to play tabletop games, and then records it!'

